name: Build & Deploy

on:
  push:
  pull_request:
  release:
    types:
      - created
      - edited

jobs:
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    needs: gradleValidation
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Test with Gradle
        run: ./gradlew classes ktlintCheck
      - name: Login to Gradle Plugin Portal
        if: "github.event_name == 'release'"
        env:
          GRADLE_CONFIG: ${{ secrets.GRADLE_CONFIG }}
        run: echo "$GRADLE_CONFIG" > ~/.gradle/gradle.properties
      - name: Gradle Publish
        if: "github.event_name == 'release'"
        run: ./gradlew publishPlugins
