name: Build & Deploy

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Test with Gradle
        run: ./gradlew classes ktlintCheck
      - name: Login to Gradle Plugin Portal
        if: "github.event_name == 'release'"
        env:
          GRADLE_CONFIG: ${{ secrets.GRADLE_CONFIG }}
        run: echo "$GRADLE_CONFIG" > ~/.gradle/gradle.properties
      - name: Gradle Publish
        if: "github.event_name == 'release'"
        run: ./gradlew publishPlugins
